# Generated by Django 6.0.5 on 2026-06-04 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido_cifrado', models.TextField()),
                ('modalidad', models.CharField(choices=[('TESTAMENTO', 'Modalidad Testamento (Fe de Vida)'), ('FECHA', 'Fecha Fija Futura')], default='TESTAMENTO', max_length=20)),
                ('fecha_liberacion', models.DateTimeField(blank=True, null=True)),
                ('frecuencia_fe_vida', models.IntegerField(blank=True, null=True)),
                ('codigo_mensaje', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('estado', models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de Pago'), ('ACTIVO', 'Activo / Custodiado'), ('LEIDO', 'Leído por Destinatario'), ('AUTODESTRUIDO', 'Eliminado Permanentemente')], default='PENDIENTE_PAGO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_primera_lectura', models.DateTimeField(blank=True, null=True)),
                ('leido_por', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.mensaje')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='mensaje',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
    ]
