# Generated by Django 6.0.5 on 2026-06-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='en_periodo_gracia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='fecha_limite_gracia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='fecha_ultima_fe_vida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de Pago'), ('ACTIVO', 'Activo / Custodiado'), ('EN_ESPERA', 'Esperando Fe de Vida (Gracia)'), ('LIBERADO', 'Habilitado para Descifrar'), ('LEIDO', 'Leído por Destinatario'), ('AUTODESTRUIDO', 'Eliminado Permanentemente')], default='PENDIENTE_PAGO', max_length=20),
        ),
    ]
